version: '2.1'
services:
  app:
    build:
      context: .
      dockerfile: ./setup/Dockerfile
    privileged: true
    shm_size: '512m'
    volumes:
        - "app:/app"
    environment:
      - PASSWORD=alcor #REPLACE WITH YOUR PASSWORD
    ports:
      - 8000:8000
volumes:
  app:
